print("╔════════════════════════╗")
print("║  Python Çalışmaları    ║")
print("║1-HESAP MAKİNESİ        ║")
print("║2-OYUNLAR               ║")
print("║3-ŞEKİL ÇİZDİRME        ║")
print("║4-TAKVİM                ║")
print("║5-RİTMİK SAYMA          ║")
print("║6-NOT HESAPLAMA         ║")
print("║7-ÇARPIM TABLOSU        ║")
print("║8-BMI HESAPLAMA         ║")
print("║9-DÖVİZ DURUMU          ║")
print("║10-SICAKLIK ÇEVİRME     ║")
print("║11-ÇIKIŞ  (e)           ║")
print("║  Seçiminizi Yapınız    ║")
print("╚════════════════════════╝")
print("Seçiminiz:")
input()
#deneme
#deneme
#deneme
